AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3Bucket:
    Description: S3 Bucket with Lambda source
    Type: String
  S3GlobeePaymentKey:
    Description: Path of the source code .zip file
    Type: String

Resources:
  # DynamoDB tables
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Inventory
      AttributeDefinitions:
        - AttributeName: TicketTierName
          AttributeType: "S"
      KeySchema:
        - AttributeName: TicketTierName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  AttendeesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Attendees
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: "S"
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  PurchasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Purchases
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: "S"
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  # IAM Roles
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "1"
                Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Inventory*
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Attendees*
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Resources*

  # Lambdas & Lambda permissions
  GlobeePaymentFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3GlobeePaymentKey
      Handler: globeePayment
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs8.10

  GlobeePaymentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt GlobeePaymentFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/globee-payment

  # API Gateway API, Resources, and Methods
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: crypto-conference-payments
      Description: Crypto Conference Website Payments

  GlobeePaymentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: globee-payment
      RestApiId: !Ref RestApi

  GlobeeOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref GlobeePaymentResource
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'" # RESTRICT TO SITE BEFORE PROD!
            ResponseTemplates:
              application/json: ""
            StatusCode: "200"
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{"statusCode":200}'
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: "200"

  GlobeePaymentPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref GlobeePaymentResource
      RestApiId: !Ref RestApi
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GlobeePaymentFunction.Arn}/invocations
        IntegrationResponses:
          - ResponseTemplates:
              application/json: "$input.json('$.body')"
            StatusCode: "200"
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: "$input.json('$.body')"
      MethodResponses:
        - ResponseModels:
            application/json: !Ref GlobeePaymentModel
          StatusCode: "200"

  # API Gateway Models
  GlobeePaymentModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref RestApi
      ContentType: application/json
      Description: Inputs for crypto payment with globee
      Name: GlobeePaymentModel
      Schema:
        "$schema": http://json-schema.org/draft-04/schema#
        title: GlobeePaymentModel
        type: object
        properties:
          status:
            type: string
          redirect_url:
            type: string
          success_url:
            type: string
  # API Gateway Deployments
  RestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: v1
