AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3Bucket:
    Description: S3 Bucket with Lambda source
    Type: String
  TicketPaymentsKey:
    Description: Path of the source code .zip file to process Globee payments
    Type: String
  S3InitKey:
    Description: Path of the source code .zip file to load the initial db state
    Type: String

Resources:
  # DynamoDB table
  CryptoConTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CryptoCon
      AttributeDefinitions:
        - AttributeName: PartitionKey
          AttributeType: "S"
        - AttributeName: SortKey
          AttributeType: "S"
      KeySchema:
        - AttributeName: PartitionKey
          KeyType: HASH
        - AttributeName: SortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: True

  # IAM Roles
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "1"
                Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
        - PolicyName: dynamodb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "2"
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/CryptoCon*

  # Lambdas & Lambda permissions
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3InitKey
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs8.10

  GlobeePaymentFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref TicketPaymentsKey
      Handler: index.globeePayment
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs8.10

  GlobeeWebhookFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref TicketPaymentsKey
      Handler: index.globeePaymentWebhook
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs8.10

  TicketInfoFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref TicketPaymentsKey
      Handler: index.ticketPricesAndInventory
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs8.10

  GlobeePaymentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt GlobeePaymentFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/globee-payment

  GlobeeWebhookPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt GlobeeWebhookFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/globee-payment/ipn-webhook

  TicketInfoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt TicketInfoFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/ticket-info

  # API Gateway API, Resources, and Methods
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: crypto-conference-payments
      Description: Crypto Conference Website Payments

  GlobeePaymentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: globee-payment
      RestApiId: !Ref RestApi

  GlobeeOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref GlobeePaymentResource
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'" # RESTRICT TO SITE BEFORE PROD!
            ResponseTemplates:
              application/json: ""
            StatusCode: "200"
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{"statusCode":200}'
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: "200"

  GlobeePaymentPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref GlobeePaymentResource
      RestApiId: !Ref RestApi
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GlobeePaymentFunction.Arn}/invocations

  GlobeePaymentWebhookResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref GlobeePaymentResource
      PathPart: ipn-webhook
      RestApiId: !Ref RestApi

  GlobeePaymentWebhookMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref GlobeePaymentWebhookResource
      RestApiId: !Ref RestApi
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GlobeeWebhookFunction.Arn}/invocations

  TicketInfoResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: ticket-info
      RestApiId: !Ref RestApi

  TicketInfoMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref TicketInfoResource
      RestApiId: !Ref RestApi
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TicketInfoFunction.Arn}/invocations

  # Custom
  InitTable:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: CryptoConTable
    Properties:
      ServiceToken: !GetAtt InitFunction.Arn

  # API Gateway Deployments
  RestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: v1
    DependsOn:
      - GlobeeOptionsMethod
      - GlobeePaymentPostMethod
